create table public.primary_packaging (
  packaging_id bigint generated by default as identity not null,
  unit_id bigint not null,
  dimension_cm character varying not null,
  weight_unit_kg numeric not null,
  weight_box_kg numeric not null,
  fob_price_unit numeric not null,
  fob_price_box numeric not null,
  cip_price_box numeric not null,
  packaging_datetime timestamp with time zone not null default CURRENT_TIMESTAMP,
  constraint primary_packaging_pkey primary key (packaging_id),
  constraint primary_packaging_packaging_id_key unique (packaging_id),
  constraint primary_packaging_unit_id_fkey foreign KEY (unit_id) references unity_data (unit_id)
) TABLESPACE pg_default;