create table public.purchase_order (
  order_id bigint generated by default as identity not null,
  unit_id bigint null,
  quantity_of_boxes bigint not null,
  datetime timestamp with time zone not null default CURRENT_TIMESTAMP,
  constraint purchase_order_pkey primary key (order_id),
  constraint purchase_order_order_id_key unique (order_id),
  constraint purchase_order_unit_id_fkey foreign KEY (unit_id) references unity_data (unit_id)
) TABLESPACE pg_default;