create table public.unity_data (
  unit_id bigint generated by default as identity not null,
  product_id bigint not null,
  weight_per_unit numeric not null,
  fob_price_per_unit numeric not null,
  quantity_per_box bigint not null,
  total_tablets_per_box bigint not null,
  unit_data_datetime timestamp with time zone not null default CURRENT_TIMESTAMP,
  constraint unit_data_pkey primary key (unit_id),
  constraint unit_data_unit_id_key unique (unit_id),
  constraint unit_data_product_id_fkey foreign KEY (product_id) references product (product_id)
) TABLESPACE pg_default;