create table public.brand (
  brand_id bigint generated by default as identity not null,
  brand_name character varying not null,
  brand_cnpj character varying not null,
  producer_id bigint not null,
  brand_datetime timestamp with time zone not null default CURRENT_TIMESTAMP,
  constraint brand_pkey primary key (brand_id),
  constraint brand_brand_cnpj_key unique (brand_cnpj),
  constraint brand_brand_id_key unique (brand_id),
  constraint brand_brand_name_key unique (brand_name),
  constraint brand_producer_id_fkey foreign KEY (producer_id) references user_producer (producer_id)
) TABLESPACE pg_default;