create table public.product (
  product_id bigint generated by default as identity not null,
  brand character varying not null,
  mix_of_products character varying not null,
  ncm character varying not null,
  product_datetime timestamp with time zone not null default CURRENT_TIMESTAMP,
  stamp_id bigint null,
  product_image character varying null,
  constraint product_pkey primary key (product_id),
  constraint product_product_id_key unique (product_id),
  constraint product_stamp_id_fkey foreign KEY (stamp_id) references stamp (stamp_id)
) TABLESPACE pg_default;