create table public.stamp (
  stamp_id bigint generated by default as identity not null,
  datetime timestamp with time zone not null default now(),
  stamp_name character varying not null,
  stamp_description text not null,
  constraint stamp_pkey primary key (stamp_id)
) TABLESPACE pg_default;