create table public.user_admin (
  admin_id bigint generated by default as identity not null,
  admin_username character varying not null,
  admin_password character varying not null,
  admin_email character varying not null,
  admin_datetime timestamp with time zone not null default CURRENT_TIMESTAMP,
  admin_cnpj character varying not null,
  admin_phone_number character varying not null,
  constraint user_admin_pkey primary key (admin_id),
  constraint user_admin_admin_cnpj_key unique (admin_cnpj),
  constraint user_admin_admin_id_key unique (admin_id)
) TABLESPACE pg_default;