create table public.user_buyer (
  buyer_id bigint generated by default as identity not null,
  buyer_username character varying not null,
  buyer_password character varying not null,
  buyer_email character varying not null,
  buyer_city character varying not null,
  buyer_phone_number character varying null,
  buyer_datetime timestamp with time zone not null default CURRENT_TIMESTAMP,
  buyer_cnpj character varying not null,
  constraint user_buyer_pkey primary key (buyer_id),
  constraint user_buyer_buyer_CNPJ_key unique (buyer_cnpj),
  constraint user_buyer_buyer_id_key unique (buyer_id)
) TABLESPACE pg_default;