create table public.user_producer (
  producer_id bigint generated by default as identity not null,
  producer_username character varying not null,
  producer_address character varying not null,
  producer_city character varying not null,
  producer_email character varying not null,
  producer_phone_number character varying not null,
  producer_cnpj character varying not null,
  producer_password character varying not null,
  producer_datetime timestamp with time zone not null default CURRENT_TIMESTAMP,
  constraint user_producer_pkey primary key (producer_id),
  constraint user_producer_producer_cnpj_key unique (producer_cnpj)
) TABLESPACE pg_default;