create table public.report (
  report_id bigint generated by default as identity not null,
  event_name character varying not null,
  city_country character varying not null,
  date date not null,
  event_type character varying not null,
  datetime timestamp with time zone not null,
  producer_id bigint null,
  quantity_product double precision not null,
  cdp bigint not null,
  estimated_value character varying not null,
  description text not null,
  constraint report_pkey primary key (report_id),
  constraint report_producer_id_fkey foreign KEY (producer_id) references user_producer (producer_id)
) TABLESPACE pg_default;