create table public.chat (
  message_id bigint generated by default as identity not null,
  sender_id bigint not null,
  recipient_id bigint not null,
  content text not null,
  status character varying not null,
  chat_datetime timestamp with time zone not null default CURRENT_TIMESTAMP,
  constraint chat_pkey primary key (message_id),
  constraint chat_message_id_key unique (message_id)
) TABLESPACE pg_default;