create table public.notifications (
  notification_id bigint generated by default as identity not null,
  datetime timestamp with time zone not null default now(),
  "sender_ID" bigint not null,
  "recipient_ID" bigint not null,
  content text not null,
  status character varying not null,
  constraint notifications_pkey primary key (notification_id)
) TABLESPACE pg_default;